name: Build Production
on:
  push:
    tags:
      - '*'
jobs:
  build:
    env:
      BUILD_TYPE: REL
      SENTRY_URL: ${{ secrets.SENTRY_URL }}
      SENTRY_KEY: ${{ secrets.SENTRY_KEY }}
    runs-on: windows-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          architecture: 'x64'
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Get yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Replace registry
        run: (Get-content yarn.lock) | Foreach-Object {$_ -replace "registry.nlark.com", "r.cnpmjs.org"} | Set-Content yarn.lock
      - name: Install dependencies
        run: yarn --ignore-scripts
      - name: Build native modules
        run: npm rebuild --force
      - name: Build
        run: yarn electron:build
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: cocogoat
          path: dist/*.gz
      - name: Upload unpacked
        uses: actions/upload-artifact@v2
        with:
          name: cocogoat-unpacked
          path: dist_electron/win-unpacked/